### ISSUE TITLE
PHP 5.5 compatibility

### ISSUE THREAD

**Issue by mlutfy** [KarinG/DataBC#1]
Testing on PHP 5.5, I ran into this syntax error:

[:error] [pid 7701] [client 192.168.123.1:39422] PHP Fatal error:  Arrays are not allowed in class constants in /srv/www/d7-master/sites/default/files/civicrm/ext/DataBC/CRM/DataBCGeocode/Form/Settings.php on line 15, referer: http://d7-master.dev/civicrm/admin/setting/mapping?reset=1

Seems to be caused by the syntax in:
https://github.com/KarinG/DataBC/blob/master/CRM/DataBCGeocode/Form/Settings.php#L9

**Comment by KarinG** [comment]
Ok - I've transformed it into an array to keep < PHP 5.6 happy. Can you please give it another try? Merci!
