### ISSUE TITLE
Creates broken link at "Settings - Mapping and Geocoding Providers"

### ISSUE THREAD

**Issue by brettcol** [KarinG/DataBC#6]
> Please note: if you have selected DataBC above - you will likely want to select a backup method - to GeoCode non-BC addresses - on the `DataBC admin settings page`

The above "DataBC admin settings page" links to wp-admin/databcgeocode, which creates a 404 - can I confirm if this is intended?

**Comment by KarinG** [comment]
No - that should get you to this screen -> 

![image](https://user-images.githubusercontent.com/5340555/98016046-bb64cc80-1dba-11eb-996d-2fdc95c4231c.png)

for me (on Drupal) that URL is -> `civicrm/admin/setting/databcgeocode`

I'll have a look - perhaps I inadvertently hardcoded something

**Comment by brettcol** [comment]
Could be that it doesn't like my WordPress install

**Comment by KarinG** [comment]
I'm checking with some WP colleagues - I don't use Wordpress myself. It looks like your WP is loosing the civicrm/admin/setting bit - can you try and put that in manually?

**Comment by MikeyMJCO** [comment]
This should be fixed by #7

**Comment by brettcol** [comment]
Manually navigating to the url wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fsetting%2Fdatabcgeocode does work, yes
